services:
  postgres:
    image: postgres:17-alpine
    container_name: libreriachat-postgres
    environment:
      POSTGRES_DB: libreriachat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  mongodb:
    image: mongo:8.0
    container_name: libreriachat-mongodb
    environment:
      MONGO_INITDB_DATABASE: libreriachat
    ports:
      - "27017:27017"
